#!/bin/sh
#
# Copyright (C) 2023-2024, HENSOLDT Cyber GmbH
# 
# SPDX-License-Identifier: GPL-2.0-or-later
#
# For commercial licensing, contact: info.cyber@hensoldt.net
#

echo "Starting drone mission"

/etc/drone_mission tcp://192.168.1.2:7000

echo "Done"
