#!/bin/sh
#
# Copyright 2019, Data61, CSIRO (ABN 41 687 119 230)
#
# SPDX-License-Identifier: BSD-2-Clause
#


#tcpdump &

#echo -e "\n\RUNNING Mavskd script\n"

#echo "Sleeping for 30 sec"
#sleep 30
#nc 192.168.1.1 5555 -l -u
#/etc/fly_mission udp://192.168.1.2:7000 
/etc/takeoff_and_land udp://192.168.1.2:7000

echo "Done"